name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Altere para a sua branch principal se for diferente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npx quasar build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/spa # Onde o Quasar gera o build
          branch: gh-pages # Branch de destino
